### ISSUE TITLE
App IDs are now 19 characters long

### ISSUE THREAD

**Issue by jonaswouters** [Orphoros/Statusify#1]
https://github.com/Orphoros/Statusify/blob/08151220e88717b9be31399db714cb465a7f6fe3/src/components/options/AppOptionForm.tsx#L23

Just created a new app, and I'm getting an app ID that is 19 characters long. 

Just letting you know 🫡

**Comment by Orphoros** [comment]
Oh, I see. Good to know! Thanks for the heads-up! It'll be fixed in the next release, which should be out very soon!

**Comment by Orphoros** [comment]
Fix is out in v0.0.13! Make sure to update your app! Marking the ticket as complete!
